name: tasks_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_speed_dial: ^7.0.0
  fluttertoast: ^8.2.6
  freestyle_speed_dial: ^1.0.1+2
  percent_indicator: ^4.2.3 
  provider: ^6.1.2
  equatable: ^2.0.5
  flutter_bloc: ^8.1.6
  meta: ^1.12.0
  bloc: ^8.1.4
  hydrated_bloc: ^9.1.5
  path_provider: ^2.1.4
  keyboard_detection: ^0.7.3


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/user.png
    - assets/images/To-Do-Task.png
  fonts:
    - family: Dancing Script
      fonts:
        - asset: assets/fonts/Rubik-VariableFont_wght.ttf
